###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Joao do Star Wars",
    "senha": "123",
    "email": "marcos@gmail.com",
    "telefone": "(48) 9 9999-9999"
}

###
GET http://localhost:3000/categorias

###

POST http://localhost:3000/categorias
Content-Type: application/json

{
    "nome": "DOCE"
}

###

DELETE http://localhost:3000/usuarios/1

###

PUT http://localhost:3000/usuarios/2
Content-Type: application/application/json


{
    "nome": "marcos",
    "senha": "12345",
    "emaill": "marcos@gmail.com",
    "telefone": "(4883926-7389)"

}


###

GET http://localhost:3000/receitas?page=1&limit=10


###

GET http://localhost:3000/receitas?page=2&limit=5


###
POST http://localhost:3000/receitas
Content-Type: application/json

{
    "nome": "Bolo de Cenoura",
    "modo_preparo": "corta cenoura, mistura com trigo, leva ao forno",
    "ingredientes": "cenoura, trigo e ovo",
    "usuario_id": 3,
    "categoria_id": 3,
    "porcoes": 12,
    "tempo_preparo_minutos": 45
}


###
POST http://localhost:3000/receitas
Content-Type: application/json

{
    "nome": "Bolo de Chocolate",
    "modo_preparo": "pega nescau, mistura com trigo, leva ao forno",
    "ingredientes": "nescau, trigo e ovo",
    "usuario_id": 3,
    "categoria_id": 3,
    "porcoes": 10,
    "tempo_preparo_minutos": 30
}